version: '2'
services:
  data:
    image: alpine:3.4
    volumes:
      - ./:/app/apiaxle
    command: ["true"]

  api:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
      - 3100:3100
    volumes_from:
      - data
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEBUG_MODE: true
    command: ['api', '3100']

  proxy:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
      - 3000:3000
    volumes_from:
      - data
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEBUG_MODE: true
    command: ['proxy', '3000']

  repl:
    build:
      context: .
      dockerfile: Dockerfile-development
    volumes_from:
      - data
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DEBUG_MODE: true
    command: ['repl']

  redis:
    image: redis
    ports:
      - "6379"
